"use server";

import { db } from "@/server/db";
import { classifieds, users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin-auth";
import { revalidatePath } from "next/cache";

export async function deleteClassified(id: string) {
    await requireAdmin();
    await db.delete(classifieds).where(eq(classifieds.id, id));
    revalidatePath("/admin/auditions");
}

const TITLES = ["Drummer Wanted", "Singer needed for Rock Band", "Bassist looking for band", "Guitarist Available", "Metal Band needs Vocalist"];
const TYPES = ["musician_wanted", "band_wanted"];
const INSTRUMENTS = ["Drums", "Vocals", "Bass", "Guitar", "Keys"];
const LOCATIONS = ["Melbourne", "Geelong", "Ballarat", "Bendigo"];

export async function seedClassified() {
    await requireAdmin();

    const title = TITLES[Math.floor(Math.random() * TITLES.length)];
    const type = TYPES[Math.floor(Math.random() * TYPES.length)];
    const email = `audition.${Math.floor(Math.random() * 1000)}@example.com`;

    // Create User
    const [newUser] = await db.insert(users).values({
        email,
        firstName: "Audition",
        lastName: "Poster",
    }).returning();

    // Create Classified
    await db.insert(classifieds).values({
        userId: newUser.id,
        title,
        description: "This is a test audition listing generated by the admin panel.",
        type,
        instrument: INSTRUMENTS[Math.floor(Math.random() * INSTRUMENTS.length)],
        genre: "Rock",
        location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)],
    });

    revalidatePath("/admin/auditions");
}
