"use server";

import { db } from "@/server/db";
import { professionalProfiles, users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin-auth";
import { revalidatePath } from "next/cache";

export async function deleteProfessional(id: string) {
    await requireAdmin();
    await db.delete(professionalProfiles).where(eq(professionalProfiles.id, id));
    revalidatePath("/admin/professionals");
}

const ROLES = ["Producer", "Audio Engineer", "Photographer", "Videographer", "Manager"];
const BUSINESS_NAMES = ["Sound Studio", "Visual Arts", "Manage It", "Pro Audio", "Light & Magic"];
const LOCATIONS = ["Melbourne CBD", "Fitzroy", "Brunswick", "St Kilda", "Richmond"];

export async function seedProfessional() {
    await requireAdmin();

    const role = ROLES[Math.floor(Math.random() * ROLES.length)];
    const businessName = BUSINESS_NAMES[Math.floor(Math.random() * BUSINESS_NAMES.length)] + " " + Math.floor(Math.random() * 100);
    const email = `pro.${Math.floor(Math.random() * 1000)}@example.com`;

    // Create User
    const [newUser] = await db.insert(users).values({
        email,
        firstName: "Pro",
        lastName: "User",
        userType: "professional",
    }).returning();

    // Create Profile
    await db.insert(professionalProfiles).values({
        userId: newUser.id,
        role,
        businessName,
        bio: "This is a test professional generated by the admin panel.",
        location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)],
        verified: true,
    });

    revalidatePath("/admin/professionals");
}
