"use server";

import { db } from "@/server/db";
import { bands, users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin-auth";
import { revalidatePath } from "next/cache";

export async function deleteBand(id: string) {
    await requireAdmin();
    await db.delete(bands).where(eq(bands.id, id));
    revalidatePath("/admin/bands");
}

const BAND_NAMES = ["The Rockers", "Jazz Cats", "Blue Moon", "Electric Dreams", "Sonic Wave", "Neon Lights"];
const GENRES = ["Rock", "Jazz", "Blues", "Pop", "Metal", "Indie"];
const LOCATIONS = ["Melbourne CBD", "Fitzroy", "Brunswick", "St Kilda", "Richmond"];

export async function seedBand() {
    await requireAdmin();

    const name = BAND_NAMES[Math.floor(Math.random() * BAND_NAMES.length)] + " " + Math.floor(Math.random() * 100);
    const email = `band.${Math.floor(Math.random() * 1000)}@example.com`;

    // Create User (Band Owner)
    const [newUser] = await db.insert(users).values({
        email,
        firstName: "Band",
        lastName: "Manager",
    }).returning();

    // Create Band
    await db.insert(bands).values({
        userId: newUser.id,
        name,
        bio: "This is a test band generated by the admin panel.",
        location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)],
        genres: [GENRES[Math.floor(Math.random() * GENRES.length)]],
    });

    revalidatePath("/admin/bands");
}

// CodeRabbit Audit Trigger
