"use server";

import { db } from "@/server/db";
import { musicianProfiles, users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin-auth";
import { revalidatePath } from "next/cache";

export async function deleteMusician(id: string) {
    await requireAdmin();
    await db.delete(musicianProfiles).where(eq(musicianProfiles.id, id));
    revalidatePath("/admin/musicians");
}

const FIRST_NAMES = ["James", "Sarah", "Mike", "Emily", "David", "Jessica", "Robert", "Emma"];
const LAST_NAMES = ["Smith", "dJohnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis"];
const INSTRUMENTS = ["Guitar", "Drums", "Bass", "Vocals", "Piano"];
const GENRES = ["Rock", "Jazz", "Blues", "Pop", "Metal"];
const LOCATIONS = ["Melbourne CBD", "Fitzroy", "Brunswick", "St Kilda", "Richmond"];

export async function seedMusician() {
    await requireAdmin();

    const firstName = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
    const lastName = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
    const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}.${Math.floor(Math.random() * 1000)}@example.com`;

    // Create User
    const [newUser] = await db.insert(users).values({
        email,
        firstName,
        lastName,
        userType: "musician",
    }).returning();

    // Create Profile
    await db.insert(musicianProfiles).values({
        userId: newUser.id,
        name: `${firstName} ${lastName}`,
        bio: "This is a test musician generated by the admin panel.",
        location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)],
        instruments: [INSTRUMENTS[Math.floor(Math.random() * INSTRUMENTS.length)]],
        genres: [GENRES[Math.floor(Math.random() * GENRES.length)]],
        experienceLevel: "Intermediate",
        availability: "Available Now",
    });

    revalidatePath("/admin/musicians");
}

// CodeRabbit Audit Trigger
