"use client";

import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { COSButton as Button } from "@/components/communityos/ui/cos-button"; // Fixed import
import { generateImpactInsights } from "@/lib/communityos/impact/insights";
import { ImpactKPI } from "@/lib/communityos/impact/types";
import { useTenant } from "@/components/communityos/TenantProvider";
import { Sparkles, RefreshCw, AlertTriangle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Skeleton } from "@/components/ui/skeleton";

interface InsightsPanelProps {
    kpis: ImpactKPI[];
}

export function InsightsPanel({ kpis }: InsightsPanelProps) {
    const { tenant } = useTenant();
    const [insights, setInsights] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!tenant) return;

        setIsLoading(true);
        setError(null);
        try {
            const result = await generateImpactInsights(kpis, tenant.name);
            setInsights(result);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to generate insights");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/20 dark:to-purple-950/20 border-indigo-100 dark:border-indigo-900">
            <CardHeader>
                <div className="flex items-center justify-between">
                    <div className="space-y-1">
                        <CardTitle className="flex items-center gap-2 text-indigo-900 dark:text-indigo-100">
                            <Sparkles className="h-5 w-5 text-indigo-500" />
                            AI Impact Analysis
                        </CardTitle>
                        <CardDescription>
                            Generate executive summaries and recommendations based on your KPIs.
                        </CardDescription>
                    </div>
                    {!isLoading && (
                        <Button
                            onClick={handleGenerate}
                            variant={insights ? "secondary" : "primary"}
                            icon={insights ? <RefreshCw className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />}
                        >
                            {insights ? "Regenerate" : "Generate Analysis"}
                        </Button>
                    )}
                </div>
            </CardHeader>
            <CardContent>
                {isLoading && (
                    <div className="space-y-3">
                        <Skeleton className="h-4 w-full" />
                        <Skeleton className="h-4 w-[90%]" />
                        <Skeleton className="h-4 w-[95%]" />
                        <div className="pt-4 flex items-center justify-center text-sm text-muted-foreground animate-pulse">
                            <Sparkles className="h-4 w-4 mr-2 animate-spin" />
                            Analyzing impact metrics...
                        </div>
                    </div>
                )}

                {error && (
                    <Alert variant="destructive">
                        <AlertTriangle className="h-4 w-4" />
                        <AlertTitle>Analysis Failed</AlertTitle>
                        <AlertDescription>{error}</AlertDescription>
                    </Alert>
                )}

                {insights && !isLoading && (
                    <div className="prose dark:prose-invert max-w-none">
                        <div className="whitespace-pre-wrap leading-relaxed text-sm md:text-base">
                            {insights}
                        </div>
                        <div className="mt-4 text-xs text-muted-foreground border-t pt-2 flex items-center justify-between">
                            <span>Generated by Gemini Pro</span>
                            <span>Moderation Checked</span>
                        </div>
                    </div>
                )}

                {!insights && !isLoading && !error && (
                    <div className="text-center py-8 text-muted-foreground text-sm">
                        Click "Generate Analysis" to get AI-powered insights for {tenant?.name}.
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
