/// <reference lib="webworker" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute, setCatchHandler } from 'workbox-routing';
import { clientsClaim } from 'workbox-core';
import { appShellStrategy, staticResourceStrategy, imageStrategy, apiStrategy } from './cache-strategies';

declare const self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Cleanup old caches
cleanupOutdatedCaches();

// Precache assets generated by build process
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// ---------------------------------------------------------------------------
// Route Registration
// ---------------------------------------------------------------------------

// 1. Navigation / App Shell
// Handle navigation requests with NetworkFirst strategy (load fresh HTML)
registerRoute(
    ({ request }) => request.mode === 'navigate',
    appShellStrategy
);

// 2. Static Assets (Styles, Scripts, Workers)
registerRoute(
    ({ request }) =>
        request.destination === 'style' ||
        request.destination === 'script' ||
        request.destination === 'worker',
    staticResourceStrategy
);

// 3. Images
registerRoute(
    ({ request }) => request.destination === 'image',
    imageStrategy
);

// 4. API Requests (e.g., Supabase, Next.js API routes)
// Exclude Ditto sync endpoints from this generic strategy if they need special handling,
// but for general read APIs, SWR is good.
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/') || url.hostname.includes('supabase.co'),
    apiStrategy
);

// 5. Offline Fallback
// If a navigation request fails and isn't in cache, show offline page (if precached)
setCatchHandler(async ({ event }) => {
    try {
        // Return the precached offline page if a document is being requested
        const fetchEvent = event as unknown as FetchEvent;
        if (fetchEvent.request?.destination === 'document') {
            // This assumes 'offline.html' or similar is in the precache manifest
            // or handled by appShellStrategy fallback. 
            // For Next.js PWA, usually the catch handler isn't strictly necessary 
            // if NetworkFirst handles the cache fallback effectively. 
            // We can leave this simple or expand if we have a dedicated /offline route.
            return Response.error();
        }
        return Response.error();
    } catch (error) {
        const fetchEvent = event as unknown as FetchEvent;
        console.error('Service Worker Catch Handler failed:', {
            url: fetchEvent.request?.url,
            destination: fetchEvent.request?.destination,
            error
        });
        return Response.error();
    }
});

// Listener for custom messages
self.addEventListener('message', (event) => {
    if (
        event.data &&
        typeof event.data === 'object' &&
        'type' in event.data &&
        event.data.type === 'SKIP_WAITING'
    ) {
        self.skipWaiting();
    }
});
