"use server";

import { db } from "@/server/db";
import { gigs, users } from "@shared/schema";
import { eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/admin-auth";
import { revalidatePath } from "next/cache";

export async function deleteGig(id: string) {
    await requireAdmin();
    await db.delete(gigs).where(eq(gigs.id, id));
    revalidatePath("/admin/gigs");
}

const TITLES = ["Big Rock Concert", "Jazz Night", "Acoustic Session", "Metal Fest", "Open Mic Night"];
const LOCATIONS = ["The Espy", "Corner Hotel", "Northcote Social Club", "Forum Theatre", "The Tote"];
const GENRES = ["Rock", "Jazz", "Folk", "Metal", "Indie"];

export async function seedGig() {
    await requireAdmin();

    const title = TITLES[Math.floor(Math.random() * TITLES.length)];
    const location = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];
    const email = `gig.host.${Math.floor(Math.random() * 1000)}@example.com`;

    // Create Creator
    const [newUser] = await db.insert(users).values({
        email,
        firstName: "Gig",
        lastName: "Host",
    }).returning();

    // Create Gig
    // Date next week
    const date = new Date();
    date.setDate(date.getDate() + 7);

    await db.insert(gigs).values({
        creatorId: newUser.id,
        title,
        description: "This is a test gig generated by the admin panel.",
        location,
        date,
        price: 2000, // $20
        genre: GENRES[Math.floor(Math.random() * GENRES.length)],
    });

    revalidatePath("/admin/gigs");
}
